target 'dayt2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'

end

# Auth0 Lock

pod 'Lock', '~> 1.29'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
pod 'Lock/Safari'
