import { Dimensions } from "react-native";

export default {
  images: {
    barIcon: require("../assets/images/barIcon.png"),
    cinemaIcon: require("../assets/images/cinemaIcon.png"),
    partyIcon: require("../assets/images/partyIcon.png"),
    restaurantIcon: require("../assets/images/restaurantIcon.png"),
    villageIcon: require("../assets/images/villageIcon.png"),
    heartIcon: require("../assets/images/heartIcon.png")
  },
  icons: {
    create: require("../assets/images/create_message_icon.png"),
    profile: require("../assets/images/icon_profile.png"),
    message: require("../assets/images/icon_message.png"),
    feed: require("../assets/images/feed_icon.png")
  },
  daytTypesIcons: {
    daytIcon1: require("../assets/images/daytTypesIcons/daytIcon1.png"),
    daytIcon2: require("../assets/images/daytTypesIcons/daytIcon2.png"),
    daytIcon3: require("../assets/images/daytTypesIcons/daytIcon3.png"),
    daytIcon4: require("../assets/images/daytTypesIcons/daytIcon4.png"),
    daytIcon5: require("../assets/images/daytTypesIcons/daytIcon5.png"),
    daytIcon6: require("../assets/images/daytTypesIcons/daytIcon6.png"),
    daytIcon7: require("../assets/images/daytTypesIcons/daytIcon7.png"),
    daytIcon8: require("../assets/images/daytTypesIcons/daytIcon8.png"),
    daytIcon9: require("../assets/images/daytTypesIcons/daytIcon9.png"),
    daytIcon10: require("../assets/images/daytTypesIcons/daytIcon10.png"),
    daytIcon11: require("../assets/images/daytTypesIcons/daytIcon11.png"),
    daytIcon12: require("../assets/images/daytTypesIcons/daytIcon12.png"),
    daytIcon13: require("../assets/images/daytTypesIcons/daytIcon13.png"),
    daytIcon14: require("../assets/images/daytTypesIcons/daytIcon14.png"),
    daytIcon15: require("../assets/images/daytTypesIcons/daytIcon15.png"),
    daytIcon16: require("../assets/images/daytTypesIcons/daytIcon16.png"),
    daytIcon17: require("../assets/images/daytTypesIcons/daytIcon17.png"),
    daytIcon18: require("../assets/images/daytTypesIcons/daytIcon18.png"),
    daytIcon19: require("../assets/images/daytTypesIcons/daytIcon19.png"),
    daytIcon20: require("../assets/images/daytTypesIcons/daytIcon20.png"),
    daytIcon21: require("../assets/images/daytTypesIcons/daytIcon21.png"),
    daytIcon22: require("../assets/images/daytTypesIcons/daytIcon22.png"),
    daytIcon23: require("../assets/images/daytTypesIcons/daytIcon23.png"),
    daytIcon24: require("../assets/images/daytTypesIcons/daytIcon24.png"),
    daytIcon25: require("../assets/images/daytTypesIcons/daytIcon25.png"),
    daytIcon26: require("../assets/images/daytTypesIcons/daytIcon26.png"),
    daytIcon27: require("../assets/images/daytTypesIcons/daytIcon27.png"),
    daytIcon28: require("../assets/images/daytTypesIcons/daytIcon28.png"),
    daytIcon29: require("../assets/images/daytTypesIcons/daytIcon29.png"),
    daytIcon30: require("../assets/images/daytTypesIcons/daytIcon30.png"),
    daytIcon31: require("../assets/images/daytTypesIcons/daytIcon31.png"),
    daytIcon32: require("../assets/images/daytTypesIcons/daytIcon32.png"),
    daytIcon33: require("../assets/images/daytTypesIcons/daytIcon33.png"),
    daytIcon34: require("../assets/images/daytTypesIcons/daytIcon34.png"),
    daytIcon35: require("../assets/images/daytTypesIcons/daytIcon35.png"),
    daytIcon36: require("../assets/images/daytTypesIcons/daytIcon36.png"),
    daytIcon37: require("../assets/images/daytTypesIcons/daytIcon37.png"),
    daytIcon38: require("../assets/images/daytTypesIcons/daytIcon38.png"),
    daytIcon39: require("../assets/images/daytTypesIcons/daytIcon39.png"),
    daytIcon40: require("../assets/images/daytTypesIcons/daytIcon40.png"),
    daytIcon41: require("../assets/images/daytTypesIcons/daytIcon41.png"),
    daytIcon42: require("../assets/images/daytTypesIcons/daytIcon42.png"),
    daytIcon43: require("../assets/images/daytTypesIcons/daytIcon43.png"),
    daytIcon44: require("../assets/images/daytTypesIcons/daytIcon44.png"),
    daytIcon45: require("../assets/images/daytTypesIcons/daytIcon45.png"),
    daytIcon46: require("../assets/images/daytTypesIcons/daytIcon46.png"),
    daytIcon47: require("../assets/images/daytTypesIcons/daytIcon47.png"),
    daytIcon48: require("../assets/images/daytTypesIcons/daytIcon48.png"),
    daytIcon49: require("../assets/images/daytTypesIcons/daytIcon49.png"),
    daytIcon50: require("../assets/images/daytTypesIcons/daytIcon50.png"),
    daytIcon51: require("../assets/images/daytTypesIcons/daytIcon51.png"),
    daytIcon52: require("../assets/images/daytTypesIcons/daytIcon52.png"),
    daytIcon53: require("../assets/images/daytTypesIcons/daytIcon53.png"),
    daytIcon54: require("../assets/images/daytTypesIcons/daytIcon54.png"),
    daytIcon55: require("../assets/images/daytTypesIcons/daytIcon55.png"),
    daytIcon56: require("../assets/images/daytTypesIcons/daytIcon56.png"),
    daytIcon57: require("../assets/images/daytTypesIcons/daytIcon57.png"),
    daytIcon58: require("../assets/images/daytTypesIcons/daytIcon58.png"),
    daytIcon59: require("../assets/images/daytTypesIcons/daytIcon59.png"),
    daytIcon60: require("../assets/images/daytTypesIcons/daytIcon60.png"),
    daytIcon61: require("../assets/images/daytTypesIcons/daytIcon61.png"),
    daytIcon62: require("../assets/images/daytTypesIcons/daytIcon62.png"),
    daytIcon63: require("../assets/images/daytTypesIcons/daytIcon63.png"),
    daytIcon64: require("../assets/images/daytTypesIcons/daytIcon64.png"),
    daytIcon65: require("../assets/images/daytTypesIcons/daytIcon65.png"),
    daytIcon66: require("../assets/images/daytTypesIcons/daytIcon66.png"),
    daytIcon67: require("../assets/images/daytTypesIcons/daytIcon67.png"),
    daytIcon68: require("../assets/images/daytTypesIcons/daytIcon68.png"),
    daytIcon69: require("../assets/images/daytTypesIcons/daytIcon69.png"),
    daytIcon70: require("../assets/images/daytTypesIcons/daytIcon70.png"),
    daytIcon71: require("../assets/images/daytTypesIcons/daytIcon71.png"),
    daytIcon72: require("../assets/images/daytTypesIcons/daytIcon72.png"),
    daytIcon73: require("../assets/images/daytTypesIcons/daytIcon73.png"),
    daytIcon74: require("../assets/images/daytTypesIcons/daytIcon74.png"),
    daytIcon75: require("../assets/images/daytTypesIcons/daytIcon75.png"),
    daytIcon76: require("../assets/images/daytTypesIcons/daytIcon76.png"),
    daytIcon77: require("../assets/images/daytTypesIcons/daytIcon77.png"),
    daytIcon78: require("../assets/images/daytTypesIcons/daytIcon78.png"),
    daytIcon79: require("../assets/images/daytTypesIcons/daytIcon79.png"),
    daytIcon80: require("../assets/images/daytTypesIcons/daytIcon80.png"),
    daytIcon81: require("../assets/images/daytTypesIcons/daytIcon81.png"),
    daytIcon82: require("../assets/images/daytTypesIcons/daytIcon82.png"),
    daytIcon83: require("../assets/images/daytTypesIcons/daytIcon83.png"),
    daytIcon84: require("../assets/images/daytTypesIcons/daytIcon84.png"),
    daytIcon85: require("../assets/images/daytTypesIcons/daytIcon85.png"),
    daytIcon86: require("../assets/images/daytTypesIcons/daytIcon86.png"),
    daytIcon87: require("../assets/images/daytTypesIcons/daytIcon87.png"),
    daytIcon88: require("../assets/images/daytTypesIcons/daytIcon88.png"),
    daytIcon89: require("../assets/images/daytTypesIcons/daytIcon89.png"),
    daytIcon90: require("../assets/images/daytTypesIcons/daytIcon90.png")
  },
  colors: {
    purple: "rgb(162,55,243)"
  },
  styleConstants: {
    rowHeight: 50
  },
  styleConstants: {
    rowHeight: 50,
    oneThirdWidth: Dimensions.get("window").width / 3
  },
  // baseUrl: "http://localhost:3000/",
  baseUrl: "https://daytapi-pjnegz.turbo360-vertex.com/",
  userIdKey: "logged_in_user"
};
