// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AppSyncConfig =  {
    "graphqlEndpoint": "https://gtqfztktofhxbchdhpifotiz54.appsync-api.us-east-1.amazonaws.com/graphql",
    "region": "us-east-1",
    "authenticationType": "API_KEY",
    "apiKey": "da2-tod75vhfqra3pkh6yjimdbkxje",
};

export default AppSyncConfig;