// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AppSyncConfig =  {
    "graphqlEndpoint": "https://yucnjlo3sre4njupoedx33u2zi.appsync-api.us-east-1.amazonaws.com/graphql",
    "Region": "us-east-1",
    "AuthMode": "OPENID_CONNECT",
    "ClientDatabasePrefix": "dayt2_OPENID_CONNECT"

};

export default AppSyncConfig;